# Stage 1
# build image
FROM microsoft/aspnetcore-build:2.0 AS builder
WORKDIR /source

# caches restore result by copying csproj file separately
COPY *.csproj .
RUN dotnet restore

# copies the rest of your code
COPY . .
RUN dotnet publish --output /out/ --configuration Release

# Stage 2
# runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=builder /out .
ENTRYPOINT ["dotnet", "SampleNetCoreWebApi.dll"]
